### ISSUE TITLE
No development container

### ISSUE THREAD

**Issue by thumperward** [opentffoundation/opentf#380]
### OpenTF Version

```shell
N/A
```

### Use Cases

As a software developer, I want to be able to work on various repositories including code in various languages without having to install all of the required dependencies on my machine. The [devcontainer system](https://containers.dev) enables a workflow where all dependencies are bundled in a Docker image which can integrate with supported IDEs (presently Visual Studio Code and IntelliJ). Enabling this is an simple as adding a `.devcontainer.json` file pointing to an image including the required dependencies (which for this repo is basically just Go).

### Attempted Solutions

There is presently no support for this - the developer documentation assumes the user already has the dependencies installed.

### Proposal

See #371

### References

- #371

**Comment by Hefeweizen** [comment]
[GoReleaser](https://goreleaser.com/) is in use.  It offers [docker image support](https://goreleaser.com/customization/docker/).  I would expect the project to want to use homogeneous tooling where possible.

This request isn't for a final production artifact, rather a dev artifact with development tooling available locally and preconfigured.  While part of the docker image build step could certainly do that prepartion, I would also expect a developer to need to update the environment themselves.

So two complications:
1. do we have a dev container started with permissions to build additional containers?  I imagine a certain combination of flags on the command line could have the tools inside the container talk to the host container-runtime, but that also feels like very loose security/separation.  How do others feel about that?  I'd be ok with it as long as we slap some warnings around the instructions.
2. Can we package GoReleaser into our build container?  Again, I imagine we'd want the same button consistently building all artifacts, thus the question about packaging GoReleaser.  The project is MIT licensed, but there is a paid pro version available.  Alternatively, we could provide the longer, non-goreleaser dev update instructions, and that's probably ok, as I wouldn't expect the overall environment to change that often.  Those attempting to do so are probably ok with doing it directly (rather than through our tooling).

Tagging @thschue as he has been very responsive around GoReleaser.
