### ISSUE TITLE
Release first stable opentf version as 1.5.x

### ISSUE THREAD

**Issue by pdecat** [opentffoundation/opentf#425]
Shouldn't the first stable version of opentf be a 1.5.x to indicate feature parity with upstream 1.5.x. I reckon there will be confusion if opentf 1.6.0 is published without the new features in the upcoming 1.6.0 upstream release.

Edit: maybe upstream is not the proper term anymore. How about ex-upstream, legacy or ancestor?

**Comment by cube2222** [comment]
Hey @pdecat, thanks for submitting the issue!

We've forked from the most recent MPL commit, which is much more 1.6-alpha than 1.5.x. Since then we've done work to make sure that the testing feature (main major feature coming in 1.6) is stable.

In other words, we aim for 1.6 OpenTF to have parity with legacy Terraform 1.6. Exact details on the parity are still being worked out.

**Comment by cube2222** [comment]
I'll close this for now, but feel free to reopen if you want to discuss further!

**Comment by pdecat** [comment]
Good for me, thanks!
